const songs = [
    "↑人生ゲーム↓/ゆずひこ",
    "1/6 -out of the gravity-/ぼーかりお",
    "1/6/ぼーかりおどP",
    "100万回の「I love you」/Rake",
"17才/ハルカトミユキ",
"A Whole New World/アラジン",
"Adrenaline!!!/TrySail",
"again/YUI",
"Ah Yeah!!/スキマスイッチ",
"Alchemy/Girls Dead Monster",
"always/倉木麻衣",
"Aurora/BUMP OF CHICKEN",
"Bad Apple!!/nomico",
"Be Somewhere/Buzy",
"Believe/Folder5",
"Best Friend/Kiroro",
"Best Friend/西野カナ",
"bitter/keeno",
"Blackjack/ゆちゃP",
"Blessing/halyosy",
"Blooming♡Blooming/AIKATSU☆STARS!",
"BOY MEETS GIRL/TRF",
"brave heart/林原めぐみ",
"Brave Shine/Aimer",
"Butterfly/BUMP OF CHICKEN",
"Butter-Fly/和田光司",
"Cagayake! GIRLS/桜高軽音部",
"Calc./ジミーサムP",
"Call Me Maybe/Carly Rae Jepsen",
"careless breath/EXILE",
"Carry Me Off/八王子P",
"Catch You Catch Me/グミ",
"CHANGE THE WORLD/V6",
"Chasing hearts/miwa",
"CHE.R.RY/YUI",
"CLICK/ClariS",
"clock lock works/ハチ",
"clover/hiro",
"Connecting/halyosy",
"Cosmic star/emon",
"crack/keeno",
"crossing field/LiSA",
"Crow Song/Girls Dead Monster ",
"Cry Baby/Official髭男dism",
"DAN DAN 心魅かれてく/FIELD OF VIEW",
"DAYBREAK FRONTLINE/Orangestar",
"Dear/19's Sound Factory",
"Deep in Abyss/リコ(CV:富田美憂)、レグ(CV:伊瀬茉莉也)",
"ebb and flow/Ray",
"ENDLESS STORY/REIRA starring YUNA ITO",
"EQUALロマンス/CoCo",
"Falco-ファルコ-/島谷ひとみ",
"fancy baby doll/田村ゆかり",
"Fantastic future/田村ゆかり",
"faraway/day after tomorrow",
"First Love/宇多田ヒカル",
"Flamingo/米津玄師",
"FOR REAL/徳山秀典",
"from Y to Y/ジミーサムP",
"Get Over/dream",
"Get Wild/TM NETWORK",
"GLAMOROUS SKY/中島美嘉",
"GO!!!/FLOW",
"GO/BUMP OF CHICKEN",
"God Knows.../涼宮ハルヒ(CV:平野綾)",
"Good day/足立佳奈",
"Good Time/Owl city & Carly Rae Jepsen",
"Good-bye days/YUI",
"HAKOBAKO PLAYER/アゴアニキP",
"HANABI/Mr.Children",
"Happiness/嵐",
"Happy Girl/喜多村英梨",
"Happy Halloween/Junky",
"HEART OF SWORD ～夜明け前～/T.M.Revolution",
"hectopascal/小糸侑(高田憂希),七海燈子(寿美菜子)",
"HELLO ～Paradise Kiss～/YUI",
"Hello,world!/BUMP OF CHICKEN",
"HELLO/Official髭男dism",
"Hello/ナオト・インティライミ",
"Here I am/globe",
"honey & clover club/ゆうゆ",
"HOT LIMIT/T.M.Revolution",
"I Really Like You/Carly Rae Jepsen",
"I see.../乃木坂46",
"I will find a star/ゆよゆっぺ",
"I'll be the one/HΛL",
"innocent starter/水樹奈々",
"irony/ClariS",
"JOY/YUKI",
"Just Be Friends/Dixie Flatline",
"KICK BACK/米津玄師",
"KiLLER LADY/八王子P",
"KING/Kanaria",
"KIRA☆Power/STAR ANIS",
"KISS ME BABY!!!/ELEGUMI TOKYO",
"Lap Tap Love/電ポルP",
"Laugh away/YUI",
"Lemon/米津玄師",
"Let It Go/アナと雪の女王",
"Little Wish ～lyrical step～/田村ゆかり",
"Los! Los! Los!/ターニャ・デグレチャフ(悠木碧)",
"LOVEトロピカ～ナ/Sister MAYO",
"LUVORATORRRRRY!/ギガ・れをる",
"Magic of Love/Perfume",
"Magic/Mrs. GREEN APPLE",
"MAGIC/愛内里菜",
"magnet/湊 貴大(流星P)",
"My Soul, Your Beats!/Lia",
"My SunShine/ROCK'A'TRENCH",
"Mysterious Eyes/GARNET CROW",
"M八七/米津玄師",
"No Logic/ジミーサムP",
"No pain, No game/ナノ",
"No.1/西野カナ",
"Northern lights/林原めぐみ",
"oath sign/LiSA",
"Oh My Darlin'/中ノ森BAND",
"OK!/松本梨香",
"O-Ku-Ri-Mo-No Sunday!/久川凪(CV:立花日菜)、久川颯(CV:長江里加)",
"One day/The ROOTLESS",
"One Love/嵐",
"only my railgun/fripSide",
"orion/米津玄師",
"Over soul/林原めぐみ",
"Overdose/なとり",
"OVERLAP/Kimeru",
"Override/市瀬るぽ",
"Packaged/kz",
"Panorama/なぎ",
"Period/CHEMISTRY",
"PLEASURE/華原朋美",
"POP STAR/平井堅",
"Pray/Tommy heavenly6",
"PSI-missing/川田まみ",
"ray/BUMP OF CHICKEN",
"Ready Go!/田村直美",
"Ref:rain/Aimer",
"resonance/T.M.Revolution",
"Rolling star/YUI",
"SAKURAスキップ/fourfolium",
"secret base～君がくれたもの～/ZONE",
"Secret of my heart/倉木麻衣",
"Shake it!/emon（Tes.）",
"SHINING LINE*/STAR☆ANIS",
"SIX COLORS BOY/雛形あきこ",
"SKY'S the limit/ぼくのりりっくのぼうよみ",
"SMILY/大塚 愛",
"Snow Song Show/DECO*27",
"Soar/流星P",
"soundless voice/ひとしずくP",
"SPiCa-acoustic arrange.ver-/とくP",
"SPLASH FREE/STYLE FIVE",
"Stairway Generation/Base Ball Bear",
"staple stable/戦場ヶ原ひたぎ(斎藤千和)",
"STAR☆T☆RAIN -アイ Solo Ver.-/B小町 アイ(高橋李依)",
"STARDOM!/AIKATSU☆STARS!",
"Starduster/ジミーサムP",
"Starry Heavens/day after tomorrow",
"START DASH SENSATION/AIKATSU STARS!",
"Stay Alive/エミリア(高橋李依)",
"Stellar Stellar/星街すいせい",
"Step and Go!/シグナルP",
"story/前島麻由",
"STYX HELIX/MYTH & ROID ",
"SUMMER SONG/YUI",
"Super Driver/平野綾",
"Surges/Orangestar",
"Tell Your World/kz",
"The Story of Us/Taylor Swift",
"Time after time～花舞う街で～/倉木麻衣",
"I can't stop my love for you/愛内里菜 ",
"TKGの歌/アリレム",
"Together/あきよしふみえ",
"TOMORROW/岡本真夜",
"Treasure/碧陽学園生徒会",
"trick and treat/OSTER project",
"TSUNAMI/サザンオールスターズ",
"U.S.A. /DA PUMP",
"Velonica/Aqua Timez",
"voice/CLOUD",
"VS/misono",
"WAになっておどろう/V6",
"We Are Never Ever Getting Back Together/Taylor Swift",
"What Makes You Beautiful/One Direction",
"Wind Climbing ～風にあそばれて～/奥井亜紀",
"You & Me/田村ゆかり feat. motsu from m.o.v.e",
"you/癒月",
"Your Best Friend/倉木麻衣",
"YUME日和/島谷ひとみ",
"ZERO!!/栗林みな実",
"あいうえおんがく/GReeeeN",
"アイデンティティ/秋山黄色",
"アイドル/YOASOBI",
"アウト オブ エデン/Kouhei",
"アカシア/BUMP OF CHICKEN",
"アゲハ蝶/ポルノグラフィティ",
"アスノヨゾラ哨戒班/Orangestar",
"アドベンチャー/YOASOBI",
"あなただけ見つめてる/大黒摩季",
"あの日タイムマシン/LONG SHOT PARTY ",
"アンサー/BUMP OF CHICKEN",
"あんたにあっかんべ/一二三",
"あんなに一緒だったのに/See-Saw",
"アンビバレント/Uru",
"イーガービリーバー/アヒル軍曹P",
"イエスタデイ/Official髭男dism",
"いつかきっと/ナオト・インティライミ",
"いつも何度でも/木村弓",
"いのちの名前/木村弓",
"イマジネーション/SPYAIR",
"イロトリドリ/ゆず",
"インタビュア/クワガタP",
"インドア系ならトラックメイカー/Yunomi & nicamoq",
"インフェルノ/Mrs. GREEN APPLE",
"ヴァンパイア/DECO*27",
"ウィーアー!/きただにひろし",
"ウォーアイニー/高橋瞳",
"うさぎのかぞえかた/さつきがてんこもり",
"うそつき/めざめP",
"うっせぇわ/Ado",
"うまぴょい伝説/ウマ娘",
"ウラオモテ・フォーチュン/佐倉千代(CV:小澤亜李)",
"エジソン/水曜日のカンパネラ",
"おじゃま虫/DECO*27",
"オツキミリサイタル/じん",
"おはよう。/Keno",
"おもかげ/林原めぐみ",
"オリジナルスター☆彡/STAR☆ANIS",
"オレンジ/逢坂大河(釘宮理恵)・櫛枝実乃梨(堀江由衣)・川嶋亜美(喜多村英梨)",
"お願い！シンデレラ/THE IDOLM@STER CINDERELLA GIRLS",
"お願いマッスル/紗倉ひびき(ファイルーズあい)&街雄鳴造(石川界人)",
"かくしん的☆めたまるふぉ～ぜっ!/土間うまる(田中あいみ)",
"かさなる影/Hearts Grow",
"カサブタ/千綿ヒデノリ",
"カヌレ/CHiCO with HoneyWorks",
"かまってちょーだい/まふまふ×天月",
"カラカラ/結束バンド",
"からくりピエロ/40mP",
"カルマ/BUMP OF CHICKEN",
"カレンダーガール/STAR☆ANIS",
"ギガンティックO.T.N/ギガP",
"キセキ/GReeeeN",
"ギターと孤独と蒼い惑星/結束バンド",
"きゅうくらりん/いよわ",
"キラキラ/小田和正",
"キラメキラリ/高槻やよい(仁後真耶子)",
"ギリギリchop/B'z",
"くじら12号/JUDY AND MARY",
"グロウアップ/Hysteric Blue",
"クロノスタシス/BUMP OF CHICKEN",
"けーたいみしてよ/MAISONdes",
"ケセラセラ/Mrs. GREEN APPLE",
"ゴールデンタイムラバー/スキマスイッチ",
"ココロオドル/nobodyknows+",
"ココロのちず/BOYSTYLE",
"コネクト/ClariS",
"コンピューターシティ/Perfume",
"コンプレックス・イマージュ/彩音",
"さぁ/SURFACE",
"サイノウサンプラー/電ポルP",
"サインはB/B小町 アイ (CV:高橋李依)",
"サウダージ/ポルノグラフィティ",
"サブリナ/家入レオ",
"サムライハート/SPYAIR",
"さよならごっこ/amazarashi",
"さよならメモリーズ/Supercell",
"しおり/Aqua Timez",
"シャルル/バルーン",
"シューティングスター/八王子P",
"シューティングスター/天月-あまつき-",
"シュガーソングとビターステップ/UNISON SQUARE GARDEN",
"シリョクケンサ/40mP",
"シル・ヴ・プレジデント/P丸様。",
"シルエット/KANA-BOON",
"シンデレラ/サイダーガール",
"スイートマジック/Junky feat.鏡音リン",
"すずめ/RADWIMPS",
"スタートライン! /AIKATSU☆STARS!",
"スターマーカー/KANA-BOON",
"スターライトパレード/SEKAI NO OWARI",
"ストリーミングハート/DECO*27",
"スパークル/RADWIMPS",
"セカイ/DECO*27",
"セツナトリップ/Last Note.",
"センチメンタルクライシス/halca",
"そして僕にできるコト/day after tomorrow",
"そばかす/JUDY AND MARY",
"それでも明日はやってくる/鈴木結女",
"それは小さな光のような/さユり",
"ソングオブザデッド/KANA-BOON",
"ダーリンダンス/かいりきベア",
"タイプ:ワイルド/松本梨香",
"タイムマシン/1640mP",
"タカラモノ～この声がなくなるまで～/ナオト・インティライミ",
"だから僕は音楽を辞めた/ヨルシカ",
"ただ君に晴れ/ヨルシカ",
"だってだってだって/タカノン",
"たばこ/コレサワ",
"だんご大家族/茶太",
"ダンシング☆サムライ/崎山つばさ",
"テルーの唄/手嶌葵",
"トゥインクル/Junky",
"トウキョウ・シャンディ・ランデヴ/MAISONdes",
"どこまでも～How Far I'll Go～/屋比久知奈",
"ドライフラワー/優里",
"ドラマチック/Base Ball Bear",
"トリセツ/西野カナ",
"トンデモワンダーズ/Sasakure.UK",
"ナイテタッテ/ナオト・インティライミ",
"なだめスかし Negotiation/鹿乃",
"なないろ/BUMP OF CHICKEN",
"なにが悪い/結束バンド",
"なりすましゲンガー/KulfiQ",
"なんでもないや/RADWIMPS",
"ニア/夏代孝明",
"ネトゲ廃人シュプレヒコール/さつきがてんこもり",
"ハイドアンド・シーク/19's Sound Factory",
"はいよろこんで/こっちのけんと",
"はじまりの日/スガシカオ",
"バタフライ・グラフィティ/八王子P",
"はっぴぃ にゅう にゃあ/芹沢文乃(伊藤かな恵)&梅ノ森千世(井口裕香)&霧谷希(竹達彩奈)",
"ハッピーシンセサイザ/Easy Pop",
"バトルフロンティア/高屋亜希那",
"ハネウマライダー/ポルノグラフィティ",
"パプリカ/米津玄師",
"ハルモニア/RYTHEM",
"バレンタイン・キッス/国生さゆり",
"ハロ/ハワユ/ナノウ",
"ピースサイン/米津玄師",
"ピーターパン・シンドローム/buzzG",
"ヒカリへ/miwa",
"ヒトミノチカラ/観月ありさ",
"ヒトリゴト/ClariS",
"ヒバナ/DECO*27",
"ビビっとラブ/HoneyWorks",
"ひまわりの約束/秦基博",
"ヒャダインのカカカタ カタオモイ-/ヒャダイン",
"ファンサ/mona(CV:夏川椎菜)",
"フォニイ/ツミキ",
"フタリボシ/40mP feat.初音ミク&GUMI",
"プライド革命/CHiCO with HoneyWorks",
"プライド革命/HoneyWorks",
"プラチナ/坂本真綾",
"ブラック★ロックシューター/Supercell",
"ブラッククリスマス/まふまふ",
"プラネタリウム/大塚愛",
"ブリキノダンス/日向電工",
"ブルーバード/いきものがかり",
"プレパレード/逢坂大河(釘宮理恵)&櫛枝実乃梨(堀江由衣)&川嶋亜美(喜多村英梨)",
"フレンジャー/大塚愛",
"フレンド・ライク・ミー/アラジン",
"ふわふわ♪/牧野由依",
"ふわふわ時間/放課後ティータイム",
"ベテルギウス/優里",
"ベノム/かいりきベア",
"ホウキ雲/RYTHEM",
"ボクノート/スキマスイッチ",
"ボクラの冒険/Kids Alive",
"ホシノウタ/とくP",
"ホログラム/NICO Touches the Walls",
"ホワイトノイズ/Official髭男dism",
"マーシャル・マキシマイザー/柊マグネタイト",
"またあした/ふわりP",
"マル・マル・モリ・モリ!/薫と友樹、たまにムック。",
"ミカヅキ/さユり",
"ミックスナッツ/Official髭男dism",
"ミュージック・アワー/ポルノグラフィティ",
"ミュージックミュージック/とあ",
"ミライチズ/夜のひと笑い",
"ム責任集合体/マサラダ",
"めいど・うぃず・どらごんず/スーパーちょろゴンず",
"メグメル/riya",
"メランコリック/Junky",
"メリッサ/ポルノグラフィティ",
"メルト/supercell",
"メンタルチェンソー/かいりきベア",
"もうそう えくすぷれす/千石撫子(花澤香菜)",
"モノクロアクト/doriko",
"モノクロのキス/シド",
"ゆるふわ樹海ガール/石風呂",
"ようかい体操第一/Dream5",
"ようこそジャパリパークへ/大石昌良",
"ライオン/May'n/中島愛",
"ラブ・ストーリーは突然に/小田和正",
"ラブチーノ/Junky",
"リアルワールド/nano.RIPE",
"リテラチュア/上田麗奈",
"リブート/miwa",
"リライト/ASIAN KUNG-FU GENERATION",
"ロキ/みきとP",
"ロストワンの号哭/Neru",
"ロミオとシンデレラ/doriko",
"ロメオ/LIP×LIP",
"ロンリーユニバース/Aqu3ra",
"わたしの恋はホッチキス/放課後ティータイム",
"一番の宝物/karuta",
"一輪の花/ふみP",
"乙女解剖/DECO*27",
"二人三脚/misono",
"二足歩行/DECO*27",
"人生リセットボタン/kemu",
"人生リセットボタンぽちーw/沙花叉クロヱ",
"人柱アリス/雪那(歪P)",
"丸の内サディスティック/椎名林檎",
"千の夜をこえて/Aqua Timez",
"千本桜/黒うさP",
"夕立のりぼん/みきとP",
"大切な人/Rake",
"小さな手のひら/Lia",
"小さな恋のうた/MONGOL800",
"小夜子/みきとP",
"今ちょっとだけ話題の神様/HoneyWorks",
"天ノ弱/164",
"天地ガエシ/NICO Touches the Walls",
"天体観測/BUMP OF CHICKEN",
"太陽曰く燃えよカオス/後ろから這いより隊G",
"心拍数#0822/蝶々P",
"月光/鬼束ちひろ",
"月光花/Janne Da Arc",
"月花/nano.RIPE",
"月虹/BUMP OF CHICKEN",
"火炎/女王蜂",
"世田谷ナイトサファリ/みきとP",
"世界に一つだけの花/SMAP",
"世界はそれを愛と呼ぶんだぜ/サンボマスター",
"世界寿命と最後の一日/スズム",
"以心電信/ORANGE RANGE",
"可愛くてごめん/HoneyWorks",
"可愛くなりたい/CHiCO with HoneyWorks",
"右肩の蝶/のりぴー",
"平行線/Eve",
"打上花火/米津玄師",
"未来コネクション/ЯeaL",
"生まれてはじめて/アナと雪の女王",
"白金ディスコ/阿良々木月火(井口裕香)",
"吉原ラメント/亜沙",
"名前のない怪物/EGOIST",
"回る空うさぎ/Orangestar",
"妄想感傷代償連盟/DECO*27",
"気まぐれロマンティック/いきものがかり",
"気分上々↑↑/mihimaru GT",
"灰色と青/米津玄師",
"君＝花/pigstar",
"君じゃなきゃダメみたい/オーイシマサヨシ",
"君という光/GARNET CROW",
"君のそばで～ヒカリのテーマ～/グリン",
"君の知らない物語/supercell",
"君はいなせなガール/石風呂",
"忘れじの言の葉/安次嶺希和子",
"忘れてやらない/結束バンド",
"快眠！安眠！スヤリスト生活/スヤリス姫(水瀬いのり)",
"決意の朝に/Aqua Timez",
"灼け落ちない翼/多田葵 ",
"私、アイドル宣言/CHiCO with HoneyWorks",
"言ノ葉カルマ/れるりり",
"走れ！/ももいろクローバー",
"車輪の唄/BUMP OF CHICKEN",
"初めての恋が終わる時/supercell",
"命に嫌われている。/カンザキイオリ",
"命のユースティティア/Neru",
"夜に駆ける/YOASOBI",
"夜もすがら君想ふ/ころん",
"夜行性ハイズ/DECO*27",
"夜咄ディセイブ/じん",
"夜空ノムコウ/SMAP",
"夜鷹の夢/Do As Infinity",
"奇跡/GReeeeN",
"始まりの日/スガシカオ",
"季節は次々死んでいく/amazarashi",
"怪獣の花唄/Vaundy",
"放課後ストライド/Last Note.",
"明日への扉/I WiSH",
"明日晴れるかな/桑田佳祐",
"炎/LiSA",
"知らなきゃ/安月名莉子 ",
"空色デイズ/中川翔子",
"空奏列車/Orangestar",

    // 將您的歌單加入這裡
];

function selectRandomSong() {
    const randomIndex = Math.floor(Math.random() * songs.length);
    const selectedSong = songs[randomIndex];
    document.getElementById("song-result").textContent = `${selectedSong}`;
}
